suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(glue)
  library(rvest)
  library(polite)
  library(purrr)
  library(logger)
  library(DBI)
  library(dbplyr)
  library(RPostgres)
  library(openssl)
  library(testthat)
  library(cronR)
})

source('allhomes.R')
source('scd_implementation.R')